### ISSUE TITLE
queryParamsOnly transitions fail

### ISSUE THREAD

**Issue by sethkinast** [nickiaconis/ember-prefetch#1]
On this line https://github.com/nickiaconis/ember-prefetch/blob/master/addon/instance-initializers/prefetch.js#L13

You iterate through `handlerInfos`. However if the transition is `queryParamsOnly`, `handlerInfos` is null.

**Comment by nickiaconis** [comment]
I'm unfamiliar with using query params in Ember. How does the router (without prefetch) handle a query param only transition? It would help if you could create an [Ember Twiddle](https://ember-twiddle.com/) that reproduces this.

**Comment by nickiaconis** [comment]
@sethkinast -- Can you please describe how to cause a `queryParamsOnly` transition? If I am to fix this, I will need to write a test for it. PRs are always welcome of course.

**Comment by sethkinast** [comment]
Looks like Asa just PR'd the fix I suggested to you yesterday-- just checking if handlerInfos is null.

If you still want repro steps I filed a bug on our internal tracker and assigned it to you.
