### ISSUE TITLE
Error while transitioning to in-repo-engines

### ISSUE THREAD

**Issue by imnkr** [nickiaconis/ember-prefetch#140]
While updating the ember version from 3.4.3 to 3.8.2 (ember-prefetch v3.1.0).
When trying to transition to routes in in-repo-engines for the very first time, the error `route.prefetch is not a function` is thrown even if the prefetch hook is not used in those routes.

I have reproduced the issue [here](https://imnkr.github.io/prefetch-issue/)

**Comment by jackson-dean** [comment]
I had this same error. I created this PR https://github.com/nickiaconis/ember-prefetch/pull/150/files
Let's see if it is accepted.

**Comment by nickiaconis** [comment]
It sounds like #150 was replaced by #159, which has already been merged and released. Closing this as that PR should have resolved the issue, but please reopen if we've missed something.
