### ISSUE TITLE
How to include auth information in prefetch request headers?

### ISSUE THREAD

**Issue by erichaus** [nickiaconis/ember-prefetch#40]
Hello,

We're using both `ember-prefetch` and `ember-simple-auth` and I noticed that doing a hard refresh on the app after being successfully logged in results in the first network request going out without the jwt auth info in the header. It seems like this is a result of ember-simple-auth not being integrated with this package and/or vice versa.

How can I include auth information from our stored jwt in all prefetch requests?

**Comment by nickiaconis** [comment]
Comments in simplabs/ember-simple-auth#1263 make it sound like you've identified a resolution here. Please reopen if that's not the case.
